### ISSUE TITLE
Hardcoded Bearer Token

### ISSUE THREAD

**Issue by damianlegawiec** [bluebash-spree-contrib/spree-react-native#3]
Hi @anuj-bluebash 

First of all, congrats on this work! 

I believe this should not be hardcoded - https://github.com/BlueBash/spree-react-native/blob/3deca6599a3775d667c0d82055c98d61c2a690c9/src/library/utils/apiUtils.js#L13

**Comment by anuj-bluebash** [comment]
@damianlegawiec
All required changes are done :)
